---
driver:
  name: docker
  binary: /usr/bin/docker
  forward_agent: true
  require_chef_omnibus: true
  disable_upstart: false
  provision_command:
    - apt-get update
    - chown root:root /usr/bin/sudo
    - chmod 4755 /usr/bin/sudo
  use_cache: false
  remove_images: true 
  forward:
  - 9090:9090

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[myfirstcookbook::default]
    attributes:
