---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    driver:
      network:
        - [ "forwarded_port", { guest: 9090, host: 9090 }]
    run_list:
      - recipe[myfirstcookbook::default]
    attributes:
